services:
  - type: web
    name: ai-live-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_PIPER_API_URL
        value: https://ai-live-piper-backend.onrender.com
